name: mrnavdemo
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # https://pub.dev/packages/cupertino_icons
  cupertino_icons: ^1.0.3

  # https://pub.dev/packages/flex_color_scheme
  flex_color_scheme: ^2.1.1

  flutter:
    sdk: flutter

  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^0.14.0+3

  # https://pub.dev/packages/routemaster
  routemaster: ^0.9.0-dev1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
